[package]
name = "everywhen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
rand = "0.8.5"
rquickjs = { version = "0.5.1" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
